### ISSUE TITLE
Fill did not work

### ISSUE THREAD

**Issue by Slimmy82** [PancakeBot/PancakeCreator#35]
Created outline then got fill error.Here are the console screen shots.
<img width="580" alt="screen shot 2015-10-18 at 1 50 45 pm" src="https://github-cloud.s3.amazonaws.com/assets/13441968/10565498/7e446c5c-759f-11e5-8104-0039118b551b.png">
<img width="579" alt="screen shot 2015-10-18 at 1 50 38 pm" src="https://github-cloud.s3.amazonaws.com/assets/13441968/10565499/7fedf76c-759f-11e5-9ea9-52d70eef694d.png">

I started a new one, same issue. This time I also created a separate simple closed polygon and got same error. 

If you would like the .pbp I have it

**Comment by techninja** [comment]
You should be able to simply drag the PBP file to a comment here and it will attach.

This issue is known and actual just got fixed in paper.js! 
https://github.com/paperjs/paper.js/pull/806

Unfortunately, the fix is stuck in their develop branch, so we can't get it till they roll a release, which may take a little time. Till then I'll implement a quick fix to implement the cleaning function before every fill. With your "broken" PBP file I can confirm it works.

**Comment by Slimmy82** [comment]
It wont upload here as it is an unrecognized file
sent email to you

**Comment by techninja** [comment]
What? Those GitHub Guys. Only acceptable formats?! Sheesh. WIll check email for the file.

**Comment by techninja** [comment]
With this one checked off the list, see if you can't get me screenshots of the error console when you can't save a file and we'll be in great shape!

**Comment by Slimmy82** [comment]
This issue occurred again. I understand I don't have the new build with your fix, but thought it would be good to share a screenshot

<img width="1432" alt="screen shot 2015-10-19 at 10 46 15 pm" src="https://cloud.githubusercontent.com/assets/13441968/10596562/8db7818c-76b3-11e5-8360-271cbd178b9e.png">
